# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.newGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.newGameButton.setGeometry(QtCore.QRect(260, 420, 93, 28))
        self.newGameButton.setObjectName("newGameButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(260, 470, 93, 28))
        self.exitButton.setObjectName("exitButton")
        self.upLeftButton = QtWidgets.QPushButton(self.centralwidget)
        self.upLeftButton.setGeometry(QtCore.QRect(70, 370, 41, 28))
        self.upLeftButton.setObjectName("upLeftButton")
        self.upRightButton = QtWidgets.QPushButton(self.centralwidget)
        self.upRightButton.setGeometry(QtCore.QRect(120, 370, 41, 28))
        self.upRightButton.setObjectName("upRightButton")
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(30, 410, 41, 28))
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(160, 410, 41, 28))
        self.rightButton.setObjectName("rightButton")
        self.bottomLeftButton = QtWidgets.QPushButton(self.centralwidget)
        self.bottomLeftButton.setGeometry(QtCore.QRect(70, 450, 41, 28))
        self.bottomLeftButton.setObjectName("bottomLeftButton")
        self.bottomRightButton = QtWidgets.QPushButton(self.centralwidget)
        self.bottomRightButton.setGeometry(QtCore.QRect(120, 450, 41, 28))
        self.bottomRightButton.setObjectName("bottomRightButton")
        self.chooseCandyButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseCandyButton.setGeometry(QtCore.QRect(70, 510, 93, 28))
        self.chooseCandyButton.setObjectName("chooseCandyButton")
        self.currentPlayerlabel = QtWidgets.QLabel(self.centralwidget)
        self.currentPlayerlabel.setGeometry(QtCore.QRect(50, 320, 151, 20))
        self.currentPlayerlabel.setObjectName("currentPlayerlabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(770, 380, 55, 16))
        self.label.setObjectName("label")
        self.player1PointsLabel = QtWidgets.QLabel(self.centralwidget)
        self.player1PointsLabel.setGeometry(QtCore.QRect(770, 420, 111, 16))
        self.player1PointsLabel.setObjectName("player1PointsLabel")
        self.player2PointsLabel = QtWidgets.QLabel(self.centralwidget)
        self.player2PointsLabel.setGeometry(QtCore.QRect(770, 460, 111, 20))
        self.player2PointsLabel.setObjectName("player2PointsLabel")
        self.onlineButton = QtWidgets.QPushButton(self.centralwidget)
        self.onlineButton.setGeometry(QtCore.QRect(260, 370, 93, 28))
        self.onlineButton.setObjectName("onlineButton")
        self.saveHistButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveHistButton.setGeometry(QtCore.QRect(480, 370, 93, 28))
        self.saveHistButton.setObjectName("saveHistButton")
        self.loadConfButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadConfButton.setGeometry(QtCore.QRect(480, 420, 93, 28))
        self.loadConfButton.setObjectName("loadConfButton")
        self.saveConfButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveConfButton.setGeometry(QtCore.QRect(480, 470, 93, 28))
        self.saveConfButton.setObjectName("saveConfButton")
        self.portLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.portLineEdit.setGeometry(QtCore.QRect(600, 370, 113, 22))
        self.portLineEdit.setObjectName("portLineEdit")
        self.addrLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.addrLineEdit.setGeometry(QtCore.QRect(600, 420, 113, 22))
        self.addrLineEdit.setObjectName("addrLineEdit")
        self.chooseConfButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseConfButton.setGeometry(QtCore.QRect(610, 470, 93, 28))
        self.chooseConfButton.setObjectName("chooseConfButton")
        self.loadSavetButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadSavetButton.setGeometry(QtCore.QRect(370, 420, 93, 28))
        self.loadSavetButton.setObjectName("loadSavetButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.newGameButton.setText(_translate("MainWindow", "New Game"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.upLeftButton.setText(_translate("MainWindow", "u-l"))
        self.upRightButton.setText(_translate("MainWindow", "u-r"))
        self.leftButton.setText(_translate("MainWindow", "l"))
        self.rightButton.setText(_translate("MainWindow", "r"))
        self.bottomLeftButton.setText(_translate("MainWindow", "b-l"))
        self.bottomRightButton.setText(_translate("MainWindow", "b-r"))
        self.chooseCandyButton.setText(_translate("MainWindow", "Choose Candy"))
        self.currentPlayerlabel.setText(_translate("MainWindow", "Current player: Player 1"))
        self.label.setText(_translate("MainWindow", "Points:"))
        self.player1PointsLabel.setText(_translate("MainWindow", "Player 1: 0"))
        self.player2PointsLabel.setText(_translate("MainWindow", "Player 2: 0"))
        self.onlineButton.setText(_translate("MainWindow", "Online"))
        self.saveHistButton.setText(_translate("MainWindow", "Save History"))
        self.loadConfButton.setText(_translate("MainWindow", "Load Conf"))
        self.saveConfButton.setText(_translate("MainWindow", "Save Conf"))
        self.portLineEdit.setText(_translate("MainWindow", "5555"))
        self.addrLineEdit.setText(_translate("MainWindow", "localhost"))
        self.chooseConfButton.setText(_translate("MainWindow", "Choose Conf"))
        self.loadSavetButton.setText(_translate("MainWindow", "Load Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
